### ISSUE TITLE
CurbExtractionSample.js Issue

### ISSUE THREAD

**Issue by MladenDj1209** [Cyclone3DR/Scripts#1]
Hello everyone!

Today I've tried to run your CurbExtractionSample.js script. Everything was fine, but now I get this error (picture). I'm not sure what went wrog, I've tried to debug, but it always breaks with the same message.
Other scripts, like  LineDetection.js run without problems.

Thanks for help!

![Unbenannt](https://user-images.githubusercontent.com/32682882/84680589-37a56300-af33-11ea-91d3-bda575a69ce3.PNG)

**Comment by Technodigit** [comment]
Hi Mladen,

my guess here is that you are facing an issue with the mechanism that is used in this script to remember the last values entered in the dlg poping up.
The mechanism used here is to store in the temp folder a file named LastCurbExtractionParameters.js
With all parameters like 
"InputStep = 1;"
The issue could be that you entered a wrong value which is now stored in this file like
"InputStep = e*ft;" ("e*ft" was entered and then stored in the file which breaks this mechanism)

And these lines in this stored file are evaluated. As a result

In order to test that this is the issue you are facing I suggest 2 things:
1. Proposal 1 is that you delete the file in the temp folder
2. Proposal 2 is you skip the lines that evaluate all these lines (commenting lines 404 to 410)

Note: you can add a print(filename); after line 402 to see exactly where the temp file is created

Let us know how that goes

**Comment by MladenDj1209** [comment]
Hi,

The first suggestion solved my problem. Thank you very much!

**Comment by Technodigit** [comment]
Great to hear!!
You are the second one to report this issue. We will try to update the script so that the mechanism to save previous parameters is more reliable!
